name: My Composite Action
description: Composes a number of action steps into a single action

inputs:
  org:
    description: An organization name
    required: true
    default: octodemo

  token:
    description: GitHub Personal Access Token
    required: true

outputs:
  my_resource:
    description: A resource Identifier
    value: ${{ steps.resource_step.outputs.my_resource }}

runs:
  using: composite
  steps:
    - run: echo "Getting organization details for '${{ inputs.org }}'"
      shell: bash

    - run: |
        curl -H "Authorization: token ${{ inputs.token }}" https://api.github.com/orgs/${{ inputs.org }} > org.json
      shell: bash

    - id: export_organization
      run: exit 1
      shell: bash

    - run: echo "POST RUN STEP"
